from pathlib import Path

idx=Path('public/index.html')
enh=Path('public/enhancements.js')

s=idx.read_text(encoding='utf-8')
old='''function routeFilterText(value){\n  return String(value||"")\n    .toLowerCase()\n    .normalize("NFD").replace(/[\\u0300-\\u036f]/g,"")\n    .replace(/[^a-z0-9]+/g,"")\n    .trim();\n}\n\nfunction plannedRouteVehicleMatch(d){\n  const filter=window.__berlinPlannedVehicleFilter;\n  if(!filter||!filter.active||!Array.isArray(filter.legs)||!filter.legs.length)return true;\n\n  const vehicleLine=routeFilterText(d.line);\n  const vehicleDirection=routeFilterText(d.raw?.direction||d.raw?.destination?.name||d.raw?.destination||"");\n  const vehicleTrip=String(d.raw?.tripId||d.raw?.journeyId||d.raw?.trip?.id||"");\n\n  return filter.legs.some(leg=>{\n    const legTrip=String(leg.tripId||"");\n    if(legTrip&&vehicleTrip&&legTrip===vehicleTrip)return true;\n\n    if(!vehicleLine||vehicleLine!==routeFilterText(leg.line))return false;\n\n    const legDirection=routeFilterText(leg.direction);\n    if(!legDirection||!vehicleDirection)return false;\n    const sameDirection=vehicleDirection.includes(legDirection)||legDirection.includes(vehicleDirection);\n    if(!sameDirection)return false;\n\n    if([leg.minLat,leg.maxLat,leg.minLon,leg.maxLon].every(Number.isFinite)){\n      return d.lat>=leg.minLat&&d.lat<=leg.maxLat&&d.lon>=leg.minLon&&d.lon<=leg.maxLon;\n    }\n    return true;\n  });\n}\n'''
new='''function routeFilterText(value){\n  return String(value||"")\n    .toLowerCase()\n    .normalize("NFD").replace(/[\\u0300-\\u036f]/g,"")\n    .replace(/[^a-z0-9]+/g,"")\n    .trim();\n}\n\nfunction canonicalRouteLine(value){\n  return routeFilterText(value)\n    .replace(/^(bus|tram|strassenbahn|sbahn|ubahn|regionalbahn|regionalexpress|express)+/,"");\n}\n\nfunction angleDiff(a,b){\n  if(!Number.isFinite(Number(a))||!Number.isFinite(Number(b)))return 180;\n  let d=Math.abs((Number(a)-Number(b))%360);\n  if(d>180)d=360-d;\n  return d;\n}\n\nfunction plannedRouteVehicleMatch(d){\n  const filter=window.__berlinPlannedVehicleFilter;\n  if(!filter||!filter.active||!Array.isArray(filter.legs)||!filter.legs.length)return true;\n\n  const vehicleLine=canonicalRouteLine(d.line);\n  const vehicleDirection=routeFilterText(d.raw?.direction||d.raw?.destination?.name||d.raw?.destination||"");\n  const vehicleTrip=String(d.raw?.tripId||d.raw?.journeyId||d.raw?.trip?.id||"");\n\n  return filter.legs.some(leg=>{\n    const legTrip=String(leg.tripId||"");\n    if(legTrip&&vehicleTrip&&legTrip===vehicleTrip)return true;\n\n    if(leg.mode&&d.mode&&leg.mode!==d.mode)return false;\n    if(!vehicleLine||vehicleLine!==canonicalRouteLine(leg.line))return false;\n\n    const inArea=![leg.minLat,leg.maxLat,leg.minLon,leg.maxLon].every(Number.isFinite) ||\n      (d.lat>=leg.minLat&&d.lat<=leg.maxLat&&d.lon>=leg.minLon&&d.lon<=leg.maxLon);\n    if(!inArea)return false;\n\n    const legDirection=routeFilterText(leg.direction);\n    const textDirectionOk=Boolean(legDirection&&vehicleDirection&&\n      (vehicleDirection.includes(legDirection)||legDirection.includes(vehicleDirection)));\n    if(textDirectionOk)return true;\n\n    // VBB radar direction labels are not always formatted like journey direction labels.\n    // In that case use the vehicle's live bearing and the planned leg bearing.\n    if(Number.isFinite(Number(leg.bearing))&&Number.isFinite(Number(d.bearing))){\n      return angleDiff(d.bearing,leg.bearing)<=95;\n    }\n\n    // Last fallback: same mode + same line + inside the relevant route corridor.\n    // This is preferable to hiding every relevant vehicle when the upstream omits direction metadata.\n    return !vehicleDirection||!legDirection;\n  });\n}\n'''
assert old in s, 'old route matcher not found'
s=s.replace(old,new,1)
old_render='''  for(const [id,d] of state.vehicles){\n    if(!state.enabled.has(d.mode))continue;\n    if(!plannedRouteVehicleMatch(d))continue;\n    if(state.query&&!d.search.includes(state.query))continue;\n    if(state.focusSelected&&!isSelectedVehicle(d))continue;\n    if(!vehicleVisibleInView(d,bounds))continue;\n'''
new_render='''  const plannedFilterActive=Boolean(window.__berlinPlannedVehicleFilter?.active);\n  for(const [id,d] of state.vehicles){\n    if(!state.enabled.has(d.mode))continue;\n    if(!plannedRouteVehicleMatch(d))continue;\n    if(!plannedFilterActive&&state.query&&!d.search.includes(state.query))continue;\n    if(!plannedFilterActive&&state.focusSelected&&!isSelectedVehicle(d))continue;\n    if(!vehicleVisibleInView(d,bounds))continue;\n'''
assert old_render in s, 'render filter block not found'
s=s.replace(old_render,new_render,1)
idx.write_text(s,encoding='utf-8')

s=enh.read_text(encoding='utf-8')
old_leg='''          relevantVehicleLegs.push({\n            line:String(leg?.line?.name||leg?.line?.id||""),\n            direction:String(leg?.direction||leg?.destination?.name||""),\n            tripId:String(leg?.tripId||leg?.trip?.id||""),\n            minLat:lats.length?Math.min(...lats)-padLat:null,\n            maxLat:lats.length?Math.max(...lats)+padLat:null,\n            minLon:lons.length?Math.min(...lons)-padLon:null,\n            maxLon:lons.length?Math.max(...lons)+padLon:null\n          });\n'''
new_leg='''          const first=coords[0], last=coords[coords.length-1];\n          const toRad=x=>Number(x)*Math.PI/180;\n          const toDeg=x=>Number(x)*180/Math.PI;\n          const y=Math.sin(toRad(last[1]-first[1]))*Math.cos(toRad(last[0]));\n          const x=Math.cos(toRad(first[0]))*Math.sin(toRad(last[0]))-Math.sin(toRad(first[0]))*Math.cos(toRad(last[0]))*Math.cos(toRad(last[1]-first[1]));\n          const legBearing=(toDeg(Math.atan2(y,x))+360)%360;\n          relevantVehicleLegs.push({\n            line:String(leg?.line?.name||leg?.line?.id||""),\n            mode:product,\n            direction:String(leg?.direction||leg?.destination?.name||""),\n            tripId:String(leg?.tripId||leg?.trip?.id||""),\n            bearing:Number.isFinite(legBearing)?legBearing:null,\n            minLat:lats.length?Math.min(...lats)-padLat:null,\n            maxLat:lats.length?Math.max(...lats)+padLat:null,\n            minLon:lons.length?Math.min(...lons)-padLon:null,\n            maxLon:lons.length?Math.max(...lons)+padLon:null\n          });\n'''
assert old_leg in s, 'relevant leg block not found'
s=s.replace(old_leg,new_leg,1)
enh.write_text(s,encoding='utf-8')

Path('.github/route_vehicle_match_v2.py').unlink(missing_ok=True)
Path('.github/workflows/route-vehicle-match-v2.yml').unlink(missing_ok=True)
